esphome:
  name: lilygo
  friendly_name: lilygo e-ink display
  on_boot:
    - priority: 600
      then:
        - lambda: |-
            ESP_LOGI("boot", "=== Memory Info at Boot ===");
            ESP_LOGI("boot", "Free heap: %d bytes", heap_caps_get_free_size(MALLOC_CAP_8BIT));
            ESP_LOGI("boot", "Free PSRAM: %d bytes", heap_caps_get_free_size(MALLOC_CAP_SPIRAM));
            ESP_LOGI("boot", "Total PSRAM: %d bytes", heap_caps_get_total_size(MALLOC_CAP_SPIRAM));

  platformio_options:
    # Unless noted otherwise, based on https://github.com/Xinyuan-LilyGO/LilyGo-EPD47/blob/1eb6119fc31fcff7a6bafecb09f4225313859fc5/examples/demo/platformio.ini#L37
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 16MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    build_flags:
      - "-DBOARD_HAS_PSRAM"                    # Enable PSRAM support in code
      - "-DARDUINO_USB_CDC_ON_BOOT=1"          # Enable USB Serial on boot
      - "-mfix-esp32-psram-cache-issue"        # Hardware workaround for PSRAM cache bug

  libraries:
    - SPI

esp32:
  variant: esp32s3
  board: esp32-s3-devkitc-1

  framework:
    type: arduino # Needed for display's platform and lambda to work
    sdkconfig_options:
      # PSRAM Configuration - CRITICAL for enabling PSRAM!
      CONFIG_SPIRAM: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "16384"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      # These ensure PSRAM is actually initialized at boot
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_BOOT_INIT: "y"
      CONFIG_SPIRAM_IGNORE_NOTFOUND: "n"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "3lOPTl7UR0o3VsoD14h7Lnpd2Mvravq9TlKqcLhNrVc=" # example key

ota:
  - platform: esphome
    password: "ab46d04dc5fe3047cf3061e272a59123" # example password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Example Fallback Hotspot"
    password: "M4bS2vSbHR93"

captive_portal:


binary_sensor:
  - platform: gpio
    pin:
      number: GPIO21
      inverted: true
    name: "Button 1"
    on_press:
      - logger.log: PhysButton Pressed

external_components:
  # Use GitHub source for Home Assistant
  - source: github://dabalroman/esphome-lilygo-t547plus_esphome-2025.11
    components: ["t547"]
  # For local development, uncomment this instead:
  # source:
  #   type: local
  #   path: components/
  # components: ["t547"]

display:
  - platform: t547
    # rotation: 180
    update_interval: 30s
    lambda: |-
      it.line(0, 0, 960, 540);
